export enum TIconSize {
  XS = 'XS',
  S = 'S',
  M = 'M',
  L = 'L',
  XL = 'XL',
  XXL = 'XXL',
}

export const IconSize: { [key in TIconSize]: number } = {
  [TIconSize.XS]: 12,
  [TIconSize.S]: 14,
  [TIconSize.M]: 16,
  [TIconSize.L]: 18,
  [TIconSize.XL]: 24,
  [TIconSize.XXL]: 32,
};

export enum TIcon {
  TICK = 'tick',
  ARROW_RIGHT = 'arrow-right',
  ARROW_LEFT = 'arrow-left',
  CHAT_LEFT = 'chat-left',
  MOON = 'moon',
  SUN = 'sun',
  THEME_AUTO = 'theme-auto',
  CHAT_RIGHT = 'chat-right',
  BIN = 'bin',
  SYNC = 'sync',
  VIDEO = 'video',
  WAVE = 'wave',
  PERSON = 'person',
  ARROW_END = 'arrow-end',
  ARROW_START = 'arrow-start',
  AI = 'ai',
  SCRIPT = 'script',
  MERGE = 'merge',
  MERGE_UP = 'merge-up',
  MERGE_DOWN = 'merge-down',
  FORWARD = 'forward',
  BACKWARD = 'backward',
  ADD_FILE = 'add-file',
  UPLOAD = 'upload',
  CC = 'cc',
  WWW = 'www',
  ARROW_COPY_RIGHT = 'arrow-copy-right',
  LOADER_RUNNER = 'loader-runner',
  PANEL = 'panel',
  HISTORY_BACK = 'history-back',
  HISTORY_FORWARD = 'history-forward',
  SETTINGS = 'settings',
  EXPORT = 'export',
  RAZOR = 'razor',
  CONTEXT = 'context',
  SAVE = 'save',
  GLOSSARY = 'glossary',
  INPUT = 'input',
  OUTPUT = 'output',
  CROSS = 'cross',
  SETTINGS_AI = 'settings-ai',
  PLUS = 'plus',
  FILE = 'file',
  BRUSH = 'brush',
  EDIT = 'edit',
  TRANSLATE = 'translate',
  LOGO = 'logo',
  STEP = 'step',
  SPACING = 'spacing',
  ARROW_TOGGLE_DOWN = 'arrow-toggle-down',
  ARROW_TOGGLE_UP = 'arrow-toggle-up',
  LANGUAGE = 'language',
  UX = 'ux',
  COLUMNS = 'columns',
  FOLDER_FAVORITE = 'folder-favorite',
  ROBOT = 'robot',
  LINE_OUT = 'line-out',
  AI_FILE = 'ai-file',
  AI_EDIT = 'ai-edit',
  TIME_CONFIG = 'time-config',
  FORMAT_CSV = 'format-csv',
  FORMAT_JSON = 'format-json',
  FORMAT_SUBTITLE = 'format-subtitle',
  INSERT_BEFORE = 'insert-before',
  INSERT_AFTER = 'insert-after',
  GAUGE = 'gauge',
  REFRESH = 'refresh',
  STOP = 'stop',
  COLUMNS_2 = 'columns-2',
  COLUMNS_3 = 'columns-3',
  LABEL = 'label',
  VIDEO_ABSENT = 'video-absent',
  LANGUAGE_INTERFACE = 'language-interface',
  PROMPT = 'prompt',
  TERMINAL = 'terminal',
  CLEANUP = 'cleanup',
  DOUBLE_RIGHT = 'double-right',
  DOUBLE_TICK = 'double-tick',
}
