import { TColorAccent, TColorCustom, TColorDefinition, TColorSystem, TCSSColorValue, TShade, TThemeColorMap } from '../definitions';
import { asColor, asOpacity, asShade, ThemeVariable } from '../ThemeVariable';
import { TThemeExporter } from '../types';
import { TThemeAppChapter, TThemeAppInputsChapter, TThemeAppWindowsChapter, TThemeControlPanelChapter, TThemeEmojiPickerChapter, TThemeFormsChapter, TThemeListItemChapter, TThemeMessageChapter, TThemeTableChapter, TThemeTablesChapter, TThemeTagsChapter, TThemeTooltipChapter, TThemeVideoPlayerChapter, TThemeWaveformsChapter } from '../types/theme';
import { CSSColor, CSSVar } from '../utils';

const blackHSL: TCSSColorValue = 'hsl(0, 0%, 10%)';
const whiteHSL: TCSSColorValue = 'hsl(200, 33%, 90%)';
const WHITE: TColorDefinition = {
  [TShade.DEFAULT]: whiteHSL,
  [TShade.BRIGHT]: whiteHSL,
  [TShade.DIMM]: whiteHSL,
  [TShade.PALE]: whiteHSL,
  [TShade.DARK]: whiteHSL,
  text: TColorSystem.BLACK,
};
const BLACK: TColorDefinition = {
  [TShade.DEFAULT]: blackHSL,
  [TShade.DIMM]: blackHSL,
  [TShade.BRIGHT]: blackHSL,
  [TShade.PALE]: blackHSL,
  [TShade.DARK]: blackHSL,
  text: TColorSystem.WHITE,
};
const TRANSPARENT: TColorDefinition = {
  [TShade.DEFAULT]: 'transparent',
  [TShade.DIMM]: 'transparent',
  [TShade.BRIGHT]: 'transparent',
  [TShade.PALE]: 'transparent',
  [TShade.DARK]: 'transparent',
  text: TColorSystem.TEXT,
};

const ACCENT1: TColorDefinition = {
  [TShade.DEFAULT]: 'hsl(177, 90%, 30%)',
  [TShade.BRIGHT]: 'hsl(177, 100%, 40%)',
  [TShade.DIMM]: 'hsl(177, 80%, 50%)',
  [TShade.PALE]: 'hsl(177, 60%, 30%)',
  [TShade.DARK]: 'hsl(177, 80%, 80%)',
  text: TColorSystem.WHITE,
};
const ACCENT2: TColorDefinition = {
  [TShade.DEFAULT]: 'hsl(278, 90%, 40%)',
  [TShade.BRIGHT]: 'hsl(278, 100%, 40%)',
  [TShade.DIMM]: 'hsl(278, 80%, 60%)',
  [TShade.PALE]: 'hsl(278, 60%, 40%)',
  [TShade.DARK]: 'hsl(278, 80%, 80%)',
  text: TColorSystem.WHITE,
};

export const colors: TThemeColorMap = {
  [TColorCustom.ALICEBLUE]: {
    [TShade.DEFAULT]: 'hsl(198, 90%, 40%)',
    [TShade.BRIGHT]: 'hsl(198, 100%, 40%)',
    [TShade.DIMM]: 'hsl(198, 80%, 60%)',
    [TShade.PALE]: 'hsl(198, 60%, 40%)',
    [TShade.DARK]: 'hsl(198, 80%, 80%)',
    text: TColorSystem.WHITE,
  },
  [TColorCustom.AQUA]: {
    [TShade.DEFAULT]: 'hsl(162, 90%, 40%)',
    [TShade.BRIGHT]: 'hsl(162, 100%, 40%)',
    [TShade.DIMM]: 'hsl(162, 80%, 60%)',
    [TShade.PALE]: 'hsl(162, 60%, 40%)',
    [TShade.DARK]: 'hsl(162, 80%, 80%)',
    text: TColorSystem.WHITE,
  },
  [TColorCustom.BLUE]: {
    [TShade.DEFAULT]: 'hsl(207, 90%, 40%)',
    [TShade.BRIGHT]: 'hsl(207, 100%, 40%)',
    [TShade.DIMM]: 'hsl(207, 80%, 60%)',
    [TShade.PALE]: 'hsl(207, 60%, 40%)',
    [TShade.DARK]: 'hsl(207, 80%, 80%)',
    text: TColorSystem.WHITE,
  },
  [TColorCustom.BRIGHTGREEN]: {
    [TShade.DEFAULT]: 'hsl(79, 90%, 40%)',
    [TShade.BRIGHT]: 'hsl(79, 100%, 40%)',
    [TShade.DIMM]: 'hsl(79, 80%, 60%)',
    [TShade.PALE]: 'hsl(79, 60%, 40%)',
    [TShade.DARK]: 'hsl(79, 80%, 80%)',
    text: TColorSystem.WHITE,
  },
  [TColorCustom.DARKPINK]: {
    [TShade.DEFAULT]: 'hsl(329, 90%, 40%)',
    [TShade.BRIGHT]: 'hsl(329, 100%, 40%)',
    [TShade.DIMM]: 'hsl(329, 80%, 60%)',
    [TShade.PALE]: 'hsl(329, 60%, 40%)',
    [TShade.DARK]: 'hsl(329, 80%, 80%)',
    text: TColorSystem.WHITE,
  },
  [TColorCustom.EARLYNIGHT]: {
    [TShade.DEFAULT]: 'hsl(278, 90%, 40%)',
    [TShade.BRIGHT]: 'hsl(278, 100%, 40%)',
    [TShade.DIMM]: 'hsl(278, 80%, 60%)',
    [TShade.PALE]: 'hsl(278, 60%, 40%)',
    [TShade.DARK]: 'hsl(278, 80%, 80%)',
    text: TColorSystem.WHITE,
  },
  [TColorCustom.GREEN]: {
    [TShade.DEFAULT]: 'hsl(111, 75%, 40%)',
    [TShade.BRIGHT]: 'hsl(111, 100%, 40%)',
    [TShade.DIMM]: 'hsl(111, 80%, 60%)',
    [TShade.PALE]: 'hsl(111, 60%, 40%)',
    [TShade.DARK]: 'hsl(111, 80%, 80%)',
    text: TColorSystem.WHITE,
  },
  [TColorCustom.JADE]: {
    [TShade.DEFAULT]: 'hsl(174, 90%, 40%)',
    [TShade.BRIGHT]: 'hsl(174, 100%, 40%)',
    [TShade.DIMM]: 'hsl(174, 80%, 60%)',
    [TShade.PALE]: 'hsl(174, 60%, 40%)',
    [TShade.DARK]: 'hsl(174, 80%, 80%)',
    text: TColorSystem.WHITE,
  },
  [TColorCustom.MAHOGANY]: {
    [TShade.DEFAULT]: 'hsl(310, 90%, 40%)',
    [TShade.BRIGHT]: 'hsl(310, 100%, 40%)',
    [TShade.DIMM]: 'hsl(310, 80%, 60%)',
    [TShade.PALE]: 'hsl(310, 60%, 40%)',
    [TShade.DARK]: 'hsl(310, 80%, 80%)',
    text: TColorSystem.WHITE,
  },
  [TColorCustom.ORANGE]: {
    [TShade.DEFAULT]: 'hsl(29, 90%, 40%)',
    [TShade.BRIGHT]: 'hsl(29, 100%, 40%)',
    [TShade.DIMM]: 'hsl(29, 80%, 60%)',
    [TShade.PALE]: 'hsl(29, 60%, 40%)',
    [TShade.DARK]: 'hsl(29, 80%, 80%)',
    text: TColorSystem.WHITE,
  },
  [TColorCustom.PINK]: {
    [TShade.DEFAULT]: 'hsl(313, 90%, 40%)',
    [TShade.BRIGHT]: 'hsl(313, 100%, 40%)',
    [TShade.DIMM]: 'hsl(313, 80%, 60%)',
    [TShade.PALE]: 'hsl(313, 60%, 40%)',
    [TShade.DARK]: 'hsl(313, 80%, 80%)',
    text: TColorSystem.WHITE,
  },
  [TColorCustom.RED]: {
    [TShade.DEFAULT]: 'hsl(7, 90%, 40%)',
    [TShade.BRIGHT]: 'hsl(7, 100%, 40%)',
    [TShade.DIMM]: 'hsl(7, 80%, 60%)',
    [TShade.PALE]: 'hsl(7, 60%, 40%)',
    [TShade.DARK]: 'hsl(7, 80%, 80%)',
    text: TColorSystem.WHITE,
  },
  [TColorCustom.TARQUOISE]: {
    [TShade.DEFAULT]: 'hsl(168, 90%, 40%)',
    [TShade.BRIGHT]: 'hsl(168, 100%, 40%)',
    [TShade.DIMM]: 'hsl(168, 80%, 60%)',
    [TShade.PALE]: 'hsl(168, 60%, 40%)',
    [TShade.DARK]: 'hsl(168, 80%, 80%)',
    text: TColorSystem.WHITE,
  },
  [TColorCustom.VIOLET]: {
    [TShade.DEFAULT]: 'hsl(282, 90%, 40%)',
    [TShade.BRIGHT]: 'hsl(282, 100%, 40%)',
    [TShade.DIMM]: 'hsl(282, 80%, 60%)',
    [TShade.PALE]: 'hsl(282, 60%, 40%)',
    [TShade.DARK]: 'hsl(282, 80%, 80%)',
    text: TColorSystem.WHITE,
  },
  [TColorCustom.YELLOW]: {
    [TShade.DEFAULT]: 'hsl(51, 90%, 40%)',
    [TShade.BRIGHT]: 'hsl(51, 100%, 40%)',
    [TShade.DIMM]: 'hsl(51, 80%, 60%)',
    [TShade.PALE]: 'hsl(51, 60%, 40%)',
    [TShade.DARK]: 'hsl(51, 80%, 80%)',
    text: TColorSystem.WHITE,
  },
  [TColorCustom.SCARLET]: {
    [TShade.DEFAULT]: 'hsl(12, 90%, 40%)',
    [TShade.BRIGHT]: 'hsl(12, 100%, 40%)',
    [TShade.DIMM]: 'hsl(12, 80%, 60%)',
    [TShade.PALE]: 'hsl(12, 60%, 40%)',
    [TShade.DARK]: 'hsl(12, 80%, 80%)',
    text: TColorSystem.WHITE,
  },
  [TColorCustom.TANGERINE]: {
    [TShade.DEFAULT]: 'hsl(36, 90%, 40%)',
    [TShade.BRIGHT]: 'hsl(36, 100%, 40%)',
    [TShade.DIMM]: 'hsl(36, 80%, 60%)',
    [TShade.PALE]: 'hsl(36, 60%, 40%)',
    [TShade.DARK]: 'hsl(36, 80%, 80%)',
    text: TColorSystem.WHITE,
  },
  [TColorCustom.GOLD]: {
    [TShade.DEFAULT]: 'hsl(60, 90%, 40%)',
    [TShade.BRIGHT]: 'hsl(60, 100%, 40%)',
    [TShade.DIMM]: 'hsl(60, 80%, 60%)',
    [TShade.PALE]: 'hsl(60, 60%, 40%)',
    [TShade.DARK]: 'hsl(60, 80%, 80%)',
    text: TColorSystem.WHITE,
  },
  [TColorCustom.LIME]: {
    [TShade.DEFAULT]: 'hsl(84, 90%, 40%)',
    [TShade.BRIGHT]: 'hsl(84, 100%, 40%)',
    [TShade.DIMM]: 'hsl(84, 80%, 60%)',
    [TShade.PALE]: 'hsl(84, 60%, 40%)',
    [TShade.DARK]: 'hsl(84, 80%, 80%)',
    text: TColorSystem.WHITE,
  },
  [TColorCustom.CHARTREUSE]: {
    [TShade.DEFAULT]: 'hsl(108, 90%, 40%)',
    [TShade.BRIGHT]: 'hsl(108, 100%, 40%)',
    [TShade.DIMM]: 'hsl(108, 80%, 60%)',
    [TShade.PALE]: 'hsl(108, 60%, 40%)',
    [TShade.DARK]: 'hsl(108, 80%, 80%)',
    text: TColorSystem.WHITE,
  },
  [TColorCustom.FOREST]: {
    [TShade.DEFAULT]: 'hsl(132, 90%, 40%)',
    [TShade.BRIGHT]: 'hsl(132, 100%, 40%)',
    [TShade.DIMM]: 'hsl(132, 80%, 60%)',
    [TShade.PALE]: 'hsl(132, 60%, 40%)',
    [TShade.DARK]: 'hsl(132, 80%, 80%)',
    text: TColorSystem.WHITE,
  },
  [TColorCustom.MINT]: {
    [TShade.DEFAULT]: 'hsl(156, 90%, 40%)',
    [TShade.BRIGHT]: 'hsl(156, 100%, 40%)',
    [TShade.DIMM]: 'hsl(156, 80%, 60%)',
    [TShade.PALE]: 'hsl(156, 60%, 40%)',
    [TShade.DARK]: 'hsl(156, 80%, 80%)',
    text: TColorSystem.WHITE,
  },
  [TColorCustom.CYAN]: {
    [TShade.DEFAULT]: 'hsl(180, 90%, 40%)',
    [TShade.BRIGHT]: 'hsl(180, 100%, 40%)',
    [TShade.DIMM]: 'hsl(180, 80%, 60%)',
    [TShade.PALE]: 'hsl(180, 60%, 40%)',
    [TShade.DARK]: 'hsl(180, 80%, 80%)',
    text: TColorSystem.WHITE,
  },
  [TColorCustom.SKY]: {
    [TShade.DEFAULT]: 'hsl(204, 90%, 40%)',
    [TShade.BRIGHT]: 'hsl(204, 100%, 40%)',
    [TShade.DIMM]: 'hsl(204, 80%, 60%)',
    [TShade.PALE]: 'hsl(204, 60%, 40%)',
    [TShade.DARK]: 'hsl(204, 80%, 80%)',
    text: TColorSystem.WHITE,
  },
  [TColorCustom.AZURE]: {
    [TShade.DEFAULT]: 'hsl(228, 90%, 40%)',
    [TShade.BRIGHT]: 'hsl(228, 100%, 40%)',
    [TShade.DIMM]: 'hsl(228, 80%, 60%)',
    [TShade.PALE]: 'hsl(228, 60%, 40%)',
    [TShade.DARK]: 'hsl(228, 80%, 80%)',
    text: TColorSystem.WHITE,
  },
  [TColorCustom.INDIGO]: {
    [TShade.DEFAULT]: 'hsl(252, 90%, 40%)',
    [TShade.BRIGHT]: 'hsl(252, 100%, 40%)',
    [TShade.DIMM]: 'hsl(252, 80%, 60%)',
    [TShade.PALE]: 'hsl(252, 60%, 40%)',
    [TShade.DARK]: 'hsl(252, 80%, 80%)',
    text: TColorSystem.WHITE,
  },
  [TColorCustom.PURPLE]: {
    [TShade.DEFAULT]: 'hsl(276, 90%, 40%)',
    [TShade.BRIGHT]: 'hsl(276, 100%, 40%)',
    [TShade.DIMM]: 'hsl(276, 80%, 60%)',
    [TShade.PALE]: 'hsl(276, 60%, 40%)',
    [TShade.DARK]: 'hsl(276, 80%, 80%)',
    text: TColorSystem.WHITE,
  },
  [TColorCustom.FUCHSIA]: {
    [TShade.DEFAULT]: 'hsl(300, 90%, 40%)',
    [TShade.BRIGHT]: 'hsl(300, 100%, 40%)',
    [TShade.DIMM]: 'hsl(300, 80%, 60%)',
    [TShade.PALE]: 'hsl(300, 60%, 40%)',
    [TShade.DARK]: 'hsl(300, 80%, 80%)',
    text: TColorSystem.WHITE,
  },
  [TColorCustom.ROSE]: {
    [TShade.DEFAULT]: 'hsl(324, 90%, 40%)',
    [TShade.BRIGHT]: 'hsl(324, 100%, 40%)',
    [TShade.DIMM]: 'hsl(324, 80%, 60%)',
    [TShade.PALE]: 'hsl(324, 60%, 40%)',
    [TShade.DARK]: 'hsl(324, 80%, 80%)',
    text: TColorSystem.WHITE,
  },
  [TColorCustom.CRIMSON]: {
    [TShade.DEFAULT]: 'hsl(348, 90%, 40%)',
    [TShade.BRIGHT]: 'hsl(348, 100%, 40%)',
    [TShade.DIMM]: 'hsl(348, 80%, 60%)',
    [TShade.PALE]: 'hsl(348, 60%, 40%)',
    [TShade.DARK]: 'hsl(348, 80%, 80%)',
    text: TColorSystem.WHITE,
  },
  [TColorAccent.ACCENT1]: ACCENT1,
  [TColorAccent.ACCENT2]: ACCENT2,
  [TColorSystem.BLACK]: BLACK,
  [TColorSystem.WHITE]: WHITE,
  [TColorSystem.TEXT]: BLACK,
  [TColorSystem.BG]: WHITE,
  [TColorSystem.TRANSPARENT]: TRANSPARENT,
} as const;

const bevelShadow = `0 ${CSSVar('size1')} ${CSSVar('size2')} ${CSSColor(TColorSystem.BLACK, TShade.DEFAULT, 5)}`;
const bevelShadowHover = `0 ${CSSVar('size1')} ${CSSVar('size2')} ${CSSColor(TColorSystem.BLACK, TShade.DEFAULT, 5)}`;
const bevelShadowFocus = `0 ${CSSVar('size1')} ${CSSVar('size2')} ${CSSColor(TColorSystem.BLACK, TShade.DEFAULT, 5)}`;
const bevelShadowDisabled = `0 ${CSSVar('size1')} ${CSSVar('size2')} ${CSSColor(TColorSystem.BLACK, TShade.DEFAULT, 5)}`;

export const variables: TThemeExporter = () => {
  const app: TThemeAppChapter = {
    ...new ThemeVariable('appScrollbarThumbColor', CSSColor(TColorSystem.TEXT, TShade.DEFAULT, 30)).register(),
    ...new ThemeVariable('appScrollbarTrackColor', CSSColor(TColorSystem.TEXT, TShade.DEFAULT, 0)).register(),
    ...new ThemeVariable('appBgFilter', `blur(${CSSVar('blurHeavy')})`).register(),
    ...new ThemeVariable('appBgGradientStartColor', CSSColor(TColorSystem.BG, TShade.DEFAULT, 90)).register(),
    ...new ThemeVariable('appBgGradientEndColor', CSSColor(TColorSystem.BG, TShade.DEFAULT, 95)).register(),
    ...new ThemeVariable('appBgOpacity', CSSVar('opacity-95')).register(),
    ...new ThemeVariable('appBgOverlay', `linear-gradient(to bottom, ${CSSVar('appBgGradientStartColor')}, ${CSSVar('appBgGradientEndColor')})`).register(),
  };

  const mainTable: TThemeTableChapter = {
    ...new ThemeVariable('mainTableBackdrop', 'none').register(),
    ...new ThemeVariable('mainTableBgColor', CSSColor(TColorSystem.TRANSPARENT, TShade.DEFAULT, 0)).register(),
    ...new ThemeVariable('mainTableHeaderBackdrop', `blur(${CSSVar('blurHeavy')})`).register(),
    ...new ThemeVariable('mainTableHeaderBg', CSSColor(TColorSystem.BG, TShade.DEFAULT, 10)).register(),
    ...new ThemeVariable('mainTableHeaderColor', CSSColor(TColorSystem.TEXT, TShade.DEFAULT, 80)).register(),
    ...new ThemeVariable('mainTableLineBackdropBg', CSSColor(TColorSystem.TRANSPARENT, TShade.DEFAULT, 0)).register(),
    ...new ThemeVariable('mainTableLineBackdropBgFrozen', CSSColor(TColorCustom.ALICEBLUE, TShade.DARK, 20)).register(),
    ...new ThemeVariable('mainTableLineBackdropBgHover', CSSColor(TColorSystem.TRANSPARENT, TShade.DEFAULT, 5)).register(),
    // Active (currently playing) uses ACCENT2 -- ACCENT1 is reserved for focus (selected-for-editing)
    // so the two states can't be confused, matching the waveform's active/focus color split.
    ...new ThemeVariable('mainTableLineBackdropBgActive', CSSColor(TColorAccent.ACCENT2, TShade.DEFAULT, 10)).register(),
    ...new ThemeVariable('mainTableLineBackdropBgCompleted', CSSColor(TColorCustom.GREEN, TShade.DEFAULT, 5)).register(),
    ...new ThemeVariable('mainTableLineBackdropBgFocus', CSSColor(TColorSystem.BG, TShade.DEFAULT, 20)).register(),
    ...new ThemeVariable('mainTableLineBackdropBgMergeCandidate', CSSColor(TColorAccent.ACCENT2, TShade.DEFAULT, 20)).register(),
    ...new ThemeVariable('mainTableLineColor', CSSColor(TColorSystem.TEXT, TShade.DEFAULT, 100)).register(),
    ...new ThemeVariable('mainTableLineColorFrozen', CSSColor(TColorSystem.TEXT, TShade.DEFAULT, 50)).register(),
    ...new ThemeVariable('mainTableLineColorActive', CSSColor(TColorSystem.TEXT, TShade.DEFAULT, 100)).register(),
    ...new ThemeVariable('mainTableLineColorCompleted', CSSVar('mainTableLineColor')).register(),
    ...new ThemeVariable('mainTableLineColorFocus', CSSVar('mainTableLineColorActive')).register(),
    ...new ThemeVariable('mainTableLineColorMergeCandidate', CSSVar('mainTableLineColorActive')).register(),
    ...new ThemeVariable('mainTableLineColorHover', CSSVar('mainTableLineColor')).register(),
    ...new ThemeVariable('mainTableLineBackdropFilter', 'none').register(),
    ...new ThemeVariable('mainTableLineBackdropFilterFrozen', `blur(${CSSVar('blurExtreme')})`).register(),
    ...new ThemeVariable('mainTableLineBackdropFilterHover', CSSVar('mainTableLineBackdropFilter')).register(),
    ...new ThemeVariable('mainTableLineBackdropFilterFocus', `blur(${CSSVar('blurExtreme')})`).register(),
    ...new ThemeVariable('mainTableLineBackdropFilterActive', `blur(${CSSVar('blurRegular')})`).register(),
    ...new ThemeVariable('mainTableLineBackdropFilterMergeCandidate', CSSVar('mainTableLineBackdropFilter')).register(),
    ...new ThemeVariable('mainTableLineBackdropFilterCompleted', CSSVar('mainTableLineBackdropFilter')).register(),
    ...new ThemeVariable('mainTableLineBackdropOpacity', CSSVar('opacity-0')).register(),
    ...new ThemeVariable('mainTableLineBackdropOpacityFrozen', CSSVar('opacity-100')).register(),
    ...new ThemeVariable('mainTableLineBackdropOpacityCompleted', CSSVar('opacity-100')).register(),
    ...new ThemeVariable('mainTableLineBackdropOpacityHover', CSSVar('opacity-0')).register(),
    ...new ThemeVariable('mainTableLineBackdropOpacityFocus', CSSVar('opacity-100')).register(),
    ...new ThemeVariable('mainTableLineBackdropOpacityActive', CSSVar('opacity-100')).register(),
    ...new ThemeVariable('mainTableLineBackdropOpacityMergeCandidate', CSSVar('opacity-50')).register(),
    ...new ThemeVariable('mainTableLineOpacityFrozen', CSSVar('opacity-80')).register(),
    ...new ThemeVariable('mainTableLineOpacityActive', CSSVar('opacity-100')).register(),
    ...new ThemeVariable('mainTableLineOpacityFocus', CSSVar('opacity-100')).register(),
    ...new ThemeVariable('mainTableLineOpacityMergeCandidate', CSSVar('opacity-100')).register(),
    ...new ThemeVariable('mainTableLineOpacityHover', CSSVar('opacity-90')).register(),
    ...new ThemeVariable('mainTableLineOpacityCompleted', CSSVar('opacity-80')).register(),
    ...new ThemeVariable('mainTableLineOpacity', CSSVar('opacity-90')).register(),
    ...new ThemeVariable('mainTableLineBackdropBorderColor', CSSColor(TColorSystem.TRANSPARENT, TShade.DEFAULT, 0)).register(),
    ...new ThemeVariable('mainTableLineBackdropBorderColorFrozen', CSSColor(TColorSystem.TEXT, TShade.DEFAULT, 10)).register(),
    ...new ThemeVariable('mainTableLineBackdropBorderColorCompleted', CSSVar('mainTableLineBackdropBorderColor')).register(),
    ...new ThemeVariable('mainTableLineBackdropBorderColorHover', CSSVar('mainTableLineBackdropBorderColor')).register(),
    ...new ThemeVariable('mainTableLineBackdropBorderColorFocus', CSSColor(TColorSystem.TEXT, TShade.DEFAULT, 10)).register(),
    ...new ThemeVariable('mainTableLineBackdropBorderColorActive', CSSVar('mainTableLineBackdropBorderColor')).register(),
    ...new ThemeVariable('mainTableLineBackdropBorderColorMergeCandidate', CSSVar('mainTableLineBackdropBorderColor')).register(),
    ...new ThemeVariable('mainTableLineCellBg', CSSColor(TColorSystem.TRANSPARENT, TShade.DEFAULT, 0)).register(),
    ...new ThemeVariable('mainTableLineCellBgHover', CSSColor(TColorSystem.BLACK, TShade.DEFAULT, 5)).register(),
    ...new ThemeVariable('mainTableLineCellBgFocus', CSSColor(TColorSystem.BLACK, TShade.DEFAULT, 0)).register(),
    ...new ThemeVariable('mainTableLineCellBorderStyle', 'solid').register(),
    ...new ThemeVariable('mainTableLineCellBorderColor', CSSColor(TColorSystem.TEXT, TShade.DEFAULT, 10)).register(),
    ...new ThemeVariable('mainTableLineCellBorderColorFrozen', CSSVar('mainTableLineCellBorderColor')).register(),
    ...new ThemeVariable('mainTableLineCellBorderColorCompleted', CSSVar('mainTableLineCellBorderColor')).register(),
    ...new ThemeVariable('mainTableLineCellBorderColorHover', CSSVar('mainTableLineCellBorderColor')).register(),
    ...new ThemeVariable('mainTableLineCellBorderColorFocus', CSSColor(TColorSystem.TRANSPARENT, TShade.DEFAULT, 0)).register(),
    ...new ThemeVariable('mainTableLineCellBorderColorActive', CSSVar('mainTableLineCellBorderColor')).register(),
    ...new ThemeVariable('mainTableLineCellBorderColorMergeCandidate', CSSVar('mainTableLineCellBorderColor')).register(),
    ...new ThemeVariable('mainTableCharacterSelectorBg', CSSColor(TColorSystem.BLACK, TShade.DEFAULT, 5)).register(),
    ...new ThemeVariable('mainTableCharacterSelectorBgHover', CSSColor(TColorSystem.BLACK, TShade.DEFAULT, 10)).register(),
    ...new ThemeVariable('mainTableCharacterSelectorBgFocus', CSSColor(TColorSystem.BLACK, TShade.DEFAULT, 15)).register(),
    ...new ThemeVariable('mainTableCharacterSelectorOptionBg', CSSColor(TColorSystem.BLACK, TShade.DEFAULT, 20)).register(),
    ...new ThemeVariable('mainTableCharacterSelectorOptionBgActive', CSSColor(TColorSystem.WHITE, TShade.DEFAULT, 20)).register(),
    ...new ThemeVariable('mainTableCharacterSelectorOptionColor', CSSColor(TColorSystem.WHITE, TShade.DEFAULT, 80)).register(),
    ...new ThemeVariable('mainTableCharacterSelectorOptionColorActive', CSSColor(TColorSystem.BLACK, TShade.DEFAULT, 100)).register(),
    ...new ThemeVariable('mainTableCharacterSelectorScrollbarThumbColor', CSSColor(TColorSystem.TEXT, TShade.DEFAULT, 30)).register(),
    ...new ThemeVariable('mainTableCharacterSelectorScrollbarTrackColor', CSSColor(TColorSystem.TEXT, TShade.DEFAULT, 0)).register(),
  };

  const windows: TThemeAppWindowsChapter = {
    ...new ThemeVariable('windowBackdropFilter', `blur(${CSSVar('blurExtreme')})`).register(),
    ...new ThemeVariable('windowBorderColor', CSSColor(TColorAccent.ACCENT2, TShade.DEFAULT, 90)).register(),
    ...new ThemeVariable('windowBoxShadow', `inset 0 calc(${CSSVar('windowBorderWidth')} * -1) 0 ${CSSVar('windowBorderColor')}, 0 ${CSSVar('size10')} ${CSSVar('size12')} ${CSSColor(TColorSystem.BG, TShade.DEFAULT, 20)}, 0 ${CSSVar('size24')} ${CSSVar('size34')} ${CSSColor(TColorSystem.BG, TShade.DEFAULT, 40)}`).register(),
    ...new ThemeVariable('windowBackdropBg', CSSColor(TColorSystem.BG, TShade.DEFAULT, 85)).register(),
    ...new ThemeVariable('windowBg', CSSColor(TColorSystem.BG, TShade.DEFAULT, 100)).register(),
    ...new ThemeVariable('windowShadow', `inset 0 -1px 0 ${CSSColor(TColorAccent.ACCENT2, TShade.DEFAULT, 70)}, 0 ${CSSVar('size14')} ${CSSVar('size18')} ${CSSColor(TColorSystem.BG, TShade.DEFAULT, 80)} 0 ${CSSVar('size18')} ${CSSVar('size34')}  ${CSSColor(TColorAccent.ACCENT2, TShade.DEFAULT, 50)}`).register(),
    ...new ThemeVariable('windowColor', CSSColor(TColorSystem.TEXT, TShade.DEFAULT, 90)).register(),
  };

  const inputs: TThemeAppInputsChapter = {
    ...new ThemeVariable('inputBgDefault', asColor(TColorSystem.BLACK), false).register(),
    ...new ThemeVariable('inputColorOpacity', asOpacity(80), false).register(),
    ...new ThemeVariable('inputColorOpacityHover', asOpacity(90), false).register(),
    ...new ThemeVariable('inputColorOpacityFocus', asOpacity(100), false).register(),
    ...new ThemeVariable('inputColorOpacityDisabled', asOpacity(0), false).register(),
    ...new ThemeVariable('inputColorShade', asShade(TShade.DEFAULT), false).register(),
    ...new ThemeVariable('inputColorShadeHover', asShade(TShade.DEFAULT), false).register(),
    ...new ThemeVariable('inputColorShadeFocus', asShade(TShade.BRIGHT), false).register(),
    ...new ThemeVariable('inputColorShadeDisabled', asShade(TShade.DIMM), false).register(),
    ...new ThemeVariable('inputBgOpacity', asOpacity(5), false).register(),
    ...new ThemeVariable('inputBgOpacityHover', asOpacity(5), false).register(),
    ...new ThemeVariable('inputBgOpacityFocus', asOpacity(5), false).register(),
    ...new ThemeVariable('inputBgOpacityDisabled', asOpacity(5), false).register(),
    ...new ThemeVariable('inputBgShade', asShade(TShade.DEFAULT), false).register(),
    ...new ThemeVariable('inputBgShadeHover', asShade(TShade.DEFAULT), false).register(),
    ...new ThemeVariable('inputBgShadeFocus', asShade(TShade.BRIGHT), false).register(),
    ...new ThemeVariable('inputBgShadeDisabled', asShade(TShade.DIMM), false).register(),
    ...new ThemeVariable('inputBorderColorShade', asShade(TShade.DEFAULT), false).register(),
    ...new ThemeVariable('inputBorderColorShadeHover', asShade(TShade.DEFAULT), false).register(),
    ...new ThemeVariable('inputBorderColorShadeFocus', asShade(TShade.BRIGHT), false).register(),
    ...new ThemeVariable('inputBorderColorShadeDisabled', asShade(TShade.DIMM), false).register(),
    ...new ThemeVariable('inputBorderColorOpacity', asOpacity(10), false).register(),
    ...new ThemeVariable('inputBorderColorOpacityHover', asOpacity(10), false).register(),
    ...new ThemeVariable('inputBorderColorOpacityFocus', asOpacity(30), false).register(),
    ...new ThemeVariable('inputBorderColorOpacityDisabled', asOpacity(5), false).register(),
    // Toggle -- unchecked track/knob deliberately share `color` (usually the neutral TEXT color,
    // whose shades are all the identical hue and differ only by opacity -- see text/dark colors
    // above), so the track's own opacity must stay well under the knob's (toggleColorOpacity)
    // or a fully-opaque track would visually swallow the knob into itself.
    ...new ThemeVariable('toggleBgShade', asShade(TShade.PALE), false).register(),
    ...new ThemeVariable('toggleBgOpacity', asOpacity(5), false).register(),
    ...new ThemeVariable('toggleBgOpacityFocus', asOpacity(40), false).register(),
    ...new ThemeVariable('toggleBgOpacityDisabled', asOpacity(15), false).register(),
    ...new ThemeVariable('toggleEnabledBgShade', asShade(TShade.DEFAULT), false).register(),
    ...new ThemeVariable('toggleEnabledBgOpacity', asOpacity(80), false).register(),
    ...new ThemeVariable('toggleEnabledBgOpacityFocus', asOpacity(100), false).register(),
    ...new ThemeVariable('toggleEnabledBgOpacityDisabled', asOpacity(90), false).register(),
    ...new ThemeVariable('toggleColorShade', asShade(TShade.DEFAULT), false).register(),
    ...new ThemeVariable('toggleColorOpacity', asOpacity(80), false).register(),
    ...new ThemeVariable('toggleEnabledColorShade', asShade(TShade.DEFAULT), false).register(),
    ...new ThemeVariable('toggleEnabledColorOpacity', asOpacity(80), false).register(),
    ...new ThemeVariable('inputShadow', bevelShadow).register(),
    ...new ThemeVariable('inputShadowFocus', bevelShadowFocus).register(),
    ...new ThemeVariable('inputShadowHover', bevelShadowHover).register(),
    ...new ThemeVariable('inputShadowDisabled', bevelShadowDisabled).register(),
    ...new ThemeVariable('inputTextWeightLarge', CSSVar('semibold')).register(),
    ...new ThemeVariable('inputTextWeightRegular', CSSVar('semibold')).register(),
    ...new ThemeVariable('inputTextWeightSmall', CSSVar('semibold')).register(),
    ...new ThemeVariable('inputTextWeightNano', CSSVar('semibold')).register(),
    ...new ThemeVariable('inputBevelBackdropFilter', `none`).register(),
    ...new ThemeVariable('inputEmbossBackdropFilter', `none`).register(),
    ...new ThemeVariable('inputDropdownBg', CSSColor(TColorSystem.BG, TShade.DEFAULT, 90)).register(),
    ...new ThemeVariable('inputOptionBg', CSSColor(TColorSystem.TEXT, TShade.DEFAULT, 0)).register(),
    ...new ThemeVariable('inputOptionBgFocused', CSSColor(TColorSystem.TEXT, TShade.DEFAULT, 10)).register(),
    ...new ThemeVariable('inputOptionBgSelected', CSSColor(TColorSystem.TEXT, TShade.DEFAULT, 15)).register(),
    ...new ThemeVariable('inputOptionBgDisabled', CSSColor(TColorSystem.TEXT, TShade.DEFAULT, 0)).register(),
    ...new ThemeVariable('inputOptionColor', CSSColor(TColorSystem.TEXT, TShade.DEFAULT, 90)).register(),
    ...new ThemeVariable('inputOptionColorFocused', CSSColor(TColorSystem.TEXT, TShade.DEFAULT, 95)).register(),
    ...new ThemeVariable('inputOptionColorSelected', CSSColor(TColorSystem.TEXT, TShade.DEFAULT, 100)).register(),
    ...new ThemeVariable('inputOptionColorDisabled', CSSColor(TColorSystem.TEXT, TShade.DEFAULT, 20)).register(),
    ...new ThemeVariable('selectBodyBgDefault', asColor(TColorSystem.BLACK), false).register(),
    ...new ThemeVariable('selectBodyBgOpacity', asOpacity(5), false).register(),
    ...new ThemeVariable('selectBodyBgOpacityHover', asOpacity(5), false).register(),
    ...new ThemeVariable('selectBodyBgOpacityFocus', asOpacity(10), false).register(),
    ...new ThemeVariable('selectBodyBgOpacityDisabled', asOpacity(5), false).register(),
    ...new ThemeVariable('selectBodyBgShade', asShade(TShade.DEFAULT), false).register(),
    ...new ThemeVariable('selectBodyBgShadeHover', asShade(TShade.DEFAULT), false).register(),
    ...new ThemeVariable('selectBodyBgShadeFocus', asShade(TShade.BRIGHT), false).register(),
    ...new ThemeVariable('selectBodyBgShadeDisabled', asShade(TShade.DIMM), false).register(),
    ...new ThemeVariable('selectBodyColorOpacity', asOpacity(80), false).register(),
    ...new ThemeVariable('selectBodyColorOpacityHover', asOpacity(90), false).register(),
    ...new ThemeVariable('selectBodyColorOpacityFocus', asOpacity(100), false).register(),
    ...new ThemeVariable('selectBodyColorOpacityDisabled', asOpacity(50), false).register(),
    ...new ThemeVariable('selectBodyColorShade', asShade(TShade.DEFAULT), false).register(),
    ...new ThemeVariable('selectBodyColorShadeHover', asShade(TShade.DEFAULT), false).register(),
    ...new ThemeVariable('selectBodyColorShadeFocus', asShade(TShade.BRIGHT), false).register(),
    ...new ThemeVariable('selectBodyColorShadeDisabled', asShade(TShade.DIMM), false).register(),
    ...new ThemeVariable('selectBodyShadow', CSSVar('buttonShadow')).register(),
    ...new ThemeVariable('selectBodyShadowHover', CSSVar('buttonShadowHover')).register(),
    ...new ThemeVariable('selectBodyShadowFocus', CSSVar('buttonShadowFocus')).register(),
    ...new ThemeVariable('selectBodyShadowDisabled', CSSVar('buttonShadowDisabled')).register(),
    ...new ThemeVariable('inputDropdownShadow', CSSVar('buttonShadowFocus')).register(),
    ...new ThemeVariable('inputDropdownBackdropFilter', `blur(${CSSVar('blurLight')})`).register(),
    ...new ThemeVariable('buttonSpecialBg1', asColor(TColorAccent.ACCENT1), false).register(),
    ...new ThemeVariable('buttonSpecialBg2', asColor(TColorAccent.ACCENT2), false).register(),
    ...new ThemeVariable('buttonSpecialColor', asColor(TColorSystem.BG), false).register(),
    ...new ThemeVariable('buttonBgDefault', asColor(TColorSystem.TEXT), false).register(),
    ...new ThemeVariable('buttonColorOpacity', asOpacity(80), false).register(),
    ...new ThemeVariable('buttonColorOpacityHover', asOpacity(90), false).register(),
    ...new ThemeVariable('buttonColorOpacityFocus', asOpacity(100), false).register(),
    ...new ThemeVariable('buttonColorOpacityDisabled', asOpacity(50), false).register(),
    ...new ThemeVariable('buttonColorShade', asShade(TShade.DEFAULT), false).register(),
    ...new ThemeVariable('buttonColorShadeHover', asShade(TShade.DEFAULT), false).register(),
    ...new ThemeVariable('buttonColorShadeFocus', asShade(TShade.BRIGHT), false).register(),
    ...new ThemeVariable('buttonColorShadeDisabled', asShade(TShade.DIMM), false).register(),
    ...new ThemeVariable('buttonBgOpacity', asOpacity(95), false).register(),
    ...new ThemeVariable('buttonBgOpacityHover', asOpacity(100), false).register(),
    ...new ThemeVariable('buttonBgOpacityFocus', asOpacity(100), false).register(),
    ...new ThemeVariable('buttonBgOpacityDisabled', asOpacity(70), false).register(),
    ...new ThemeVariable('buttonBgShade', asShade(TShade.DEFAULT), false).register(),
    ...new ThemeVariable('buttonBgShadeHover', asShade(TShade.DEFAULT), false).register(),
    ...new ThemeVariable('buttonBgShadeFocus', asShade(TShade.BRIGHT), false).register(),
    ...new ThemeVariable('buttonBgShadeDisabled', asShade(TShade.DIMM), false).register(),
    ...new ThemeVariable('buttonBackgroundColorDefault', asColor(TColorSystem.WHITE), false).register(),
    ...new ThemeVariable('buttonShadow', bevelShadow).register(),
    ...new ThemeVariable('buttonShadowFocus', bevelShadowFocus).register(),
    ...new ThemeVariable('buttonShadowHover', bevelShadowHover).register(),
    ...new ThemeVariable('buttonShadowDisabled', bevelShadowDisabled).register(),
  };

  const messages: TThemeMessageChapter = {
    ...new ThemeVariable('messageBackdropFilterPrimary', 'none').register(),
    ...new ThemeVariable('messageBackdropFilterSecondary', `blur(${CSSVar('blurHeavy')})`).register(),
    ...new ThemeVariable('messageTextWeightLarge', CSSVar('weightTextLarge')).register(),
    ...new ThemeVariable('messageTextWeightRegular', CSSVar('weightTextRegular')).register(),
    ...new ThemeVariable('messageTextWeightNano', CSSVar('weightTextNano')).register(),
    ...new ThemeVariable('messageTextWeightSmall', CSSVar('messageTextWeightSmall')).register(),
  };

  const tags: TThemeTagsChapter = {
    ...new ThemeVariable('tagBackdropFilter', `blur(${CSSVar('blurExtreme')})`).register(),
    ...new ThemeVariable('tagBackdropFilterHover', CSSVar('tagBackdropFilter')).register(),
    ...new ThemeVariable('tagShadowRegular', 'none').register(),
    ...new ThemeVariable('tagShadowRegularHover', CSSVar('tagShadowRegular')).register(),
    ...new ThemeVariable('tagShadowLarge', CSSVar('tagShadowRegular')).register(),
    ...new ThemeVariable('tagShadowLargeHover', CSSVar('tagShadowRegularHover')).register(),
    ...new ThemeVariable('tagShadowNano', CSSVar('tagShadowRegular')).register(),
    ...new ThemeVariable('tagShadowNanoHover', CSSVar('tagShadowRegularHover')).register(),
    ...new ThemeVariable('tagShadowSmall', CSSVar('tagShadowRegular')).register(),
    ...new ThemeVariable('tagShadowSmallHover', CSSVar('tagShadowRegularHover')).register(),
    ...new ThemeVariable('tagTextWeightLarge', CSSVar('weightTextLarge')).register(),
    ...new ThemeVariable('tagTextWeightRegular', CSSVar('weightTextRegular')).register(),
    ...new ThemeVariable('tagTextWeightSmall', CSSVar('weightTextSmall')).register(),
    ...new ThemeVariable('tagTextWeightNano', CSSVar('weightTextNano')).register(),
  };

  const videoPlayer: TThemeVideoPlayerChapter = {
    ...new ThemeVariable('videoPlayerSubtitleBg', CSSColor(TColorSystem.BLACK, TShade.DEFAULT, 80)).register(),
    ...new ThemeVariable('videoPlayerSubtitleColor', CSSColor(TColorSystem.WHITE, TShade.DEFAULT, 100)).register(),
    ...new ThemeVariable('videoPlayerSubtitleBackdropFilter', `blur(${CSSVar('blurLight')})`).register(),
    ...new ThemeVariable('videoPlayerOverlayBg', CSSColor(TColorSystem.BG, TShade.DEFAULT, 60)).register(),
    ...new ThemeVariable('videoPlayerOverlayTextBg', CSSColor(TColorSystem.TEXT, TShade.DEFAULT, 90)).register(),
    ...new ThemeVariable('videoPlayerOverlayTextColor', CSSColor(TColorSystem.BG, TShade.DEFAULT, 90)).register(),
  };

  const waveforms: TThemeWaveformsChapter = {
    ...new ThemeVariable('waveformBackdropFilter', `blur(${CSSVar('blurExtreme')})`).register(),
    ...new ThemeVariable('waveformBlockBg', CSSColor(TColorSystem.BLACK, TShade.DEFAULT, 10)).register(),
    // Hover only reduces transparency of the same color -- never swaps hue.
    ...new ThemeVariable('waveformBlockBgHover', CSSColor(TColorSystem.BLACK, TShade.DEFAULT, 15)).register(),
    // Active (currently playing under the video playhead) is color-only -- no size change -- so it
    // isn't confused with the focused (selected-for-editing) block, which is the one that expands.
    ...new ThemeVariable('waveformBlockBgActive', CSSColor(TColorAccent.ACCENT2, TShade.DEFAULT, 20)).register(),
    ...new ThemeVariable('waveformBlockBgActiveHover', CSSColor(TColorAccent.ACCENT2, TShade.DEFAULT, 30)).register(),
    ...new ThemeVariable('waveformBlockBgFocused', CSSColor(TColorAccent.ACCENT1, TShade.DEFAULT, 20)).register(),
    ...new ThemeVariable('waveformBlockBgFocusedHover', CSSColor(TColorAccent.ACCENT1, TShade.DEFAULT, 30)).register(),
    ...new ThemeVariable('waveformBlockBorderColor', CSSColor(TColorSystem.BLACK, TShade.DEFAULT, 20)).register(),
    ...new ThemeVariable('waveformBlockBorderColorHover', CSSColor(TColorSystem.BLACK, TShade.DEFAULT, 30)).register(),
    ...new ThemeVariable('waveformBlockBorderColorActive', CSSColor(TColorAccent.ACCENT2, TShade.DEFAULT, 35)).register(),
    ...new ThemeVariable('waveformBlockBorderColorActiveHover', CSSColor(TColorAccent.ACCENT2, TShade.DEFAULT, 40)).register(),
    ...new ThemeVariable('waveformBlockBorderColorFocused', CSSColor(TColorAccent.ACCENT1, TShade.DEFAULT, 35)).register(),
    ...new ThemeVariable('waveformBlockBorderColorFocusedHover', CSSColor(TColorAccent.ACCENT1, TShade.DEFAULT, 40)).register(),
    ...new ThemeVariable('waveformBlockHandleColor', CSSColor(TColorAccent.ACCENT1, TShade.DEFAULT, 50)).register(),
    ...new ThemeVariable('waveformCursorColor', CSSColor(TColorAccent.ACCENT2, TShade.DEFAULT, 100)).register(),
    ...new ThemeVariable('waveformColor', BLACK[TShade.DEFAULT], false).register(),
  };

  const controlPanel: TThemeControlPanelChapter = {
    ...new ThemeVariable('controlPanelBackdrop', `blur(${CSSVar('blurExtreme')})`).register(),
    ...new ThemeVariable('controlPanelBg', CSSColor(TColorSystem.BG, TShade.DEFAULT, 20)).register(),
    ...new ThemeVariable('controlPanelBorderStyle', 'solid').register(),
    ...new ThemeVariable('controlPanelShadow', 'none').register(),
    ...new ThemeVariable('controlsPanelBorderColor', CSSColor(TColorSystem.TRANSPARENT, TShade.DEFAULT, 20)).register(),
  };

  const tables: TThemeTablesChapter = {
    ...new ThemeVariable('tableBorderColor', CSSColor(TColorSystem.TEXT, TShade.DEFAULT, 10)).register(),
    ...new ThemeVariable('tableBg', CSSColor(TColorSystem.TRANSPARENT, TShade.DEFAULT, 100)).register(),
    ...new ThemeVariable('tableCellColor', CSSColor(TColorSystem.TEXT, TShade.DEFAULT, 100)).register(),
    ...new ThemeVariable('taleCellBg', CSSColor(TColorSystem.TEXT, TShade.DEFAULT, 5)).register(),
    ...new ThemeVariable('tableHeaderBg', CSSColor(TColorSystem.TEXT, TShade.DEFAULT, 10)).register(),
    ...new ThemeVariable('tableHeaderColor', CSSColor(TColorSystem.TEXT, TShade.DEFAULT, 10)).register(),
  };

  const forms: TThemeFormsChapter = {
    ...new ThemeVariable('formRowBg', CSSColor(TColorSystem.TRANSPARENT, TShade.DEFAULT, 100)).register(),
    ...new ThemeVariable('formSectionBg', CSSColor(TColorSystem.TRANSPARENT, TShade.DEFAULT, 0)).register(),
    ...new ThemeVariable('formSectionBorderColor', CSSColor(TColorSystem.TRANSPARENT, TShade.DEFAULT, 0)).register(),
    ...new ThemeVariable('formRowBorderColor', CSSColor(TColorSystem.TRANSPARENT, TShade.DEFAULT, 100)).register(),
  };

  const tooltip: TThemeTooltipChapter = {
    ...new ThemeVariable('tooltipBg', CSSColor(TColorSystem.BG, TShade.DEFAULT, 50)).register(),
    ...new ThemeVariable('tooltipBackdropFilter', `blur(${CSSVar("blurExtreme")})`).register(),
    ...new ThemeVariable('tooltipColor', CSSColor(TColorSystem.TEXT, TShade.DEFAULT, 95)).register(),
    ...new ThemeVariable('tooltipArrowColor', CSSColor(TColorSystem.BG, TShade.DEFAULT, 90)).register(),
    
  };

  const emojiPicker: TThemeEmojiPickerChapter = {
    ...new ThemeVariable('emojiPickerBg', CSSColor(TColorSystem.BG, TShade.DEFAULT, 100)).register(),
    ...new ThemeVariable('emojiPickerBorderColor', CSSColor(TColorSystem.TEXT, TShade.DEFAULT, 10)).register(),
    ...new ThemeVariable('emojiPickerCategoryFontColor', CSSColor(TColorSystem.TEXT, TShade.DEFAULT, 90)).register(),
    ...new ThemeVariable('emojiPickerIndicatorColor', CSSColor(TColorAccent.ACCENT1, TShade.DEFAULT, 100)).register(),
    ...new ThemeVariable('emojiPickerInputBorderColor', CSSColor(TColorSystem.TEXT, TShade.DEFAULT, 20)).register(),
    ...new ThemeVariable('emojiPickerInputFontColor', CSSColor(TColorSystem.TEXT, TShade.DEFAULT, 90)).register(),
    ...new ThemeVariable('emojiPickerInputPlaceholderColor', CSSColor(TColorSystem.TEXT, TShade.DEFAULT, 40)).register(),
    ...new ThemeVariable('emojiPickerOutlineColor', CSSColor(TColorAccent.ACCENT1, TShade.DEFAULT, 60)).register(),
    ...new ThemeVariable('emojiPickerButtonHoverBg', CSSColor(TColorSystem.TEXT, TShade.DEFAULT, 5)).register(),
    ...new ThemeVariable('emojiPickerButtonActiveBg', CSSColor(TColorSystem.TEXT, TShade.DEFAULT, 10)).register(),
  };

  const listItem: TThemeListItemChapter = {
    ...new ThemeVariable('listItemBgShade', asShade(TShade.DEFAULT), false).register(),
    ...new ThemeVariable('listItemBgOpacity', asOpacity(5), false).register(),
    ...new ThemeVariable('listItemBgShadeHover', asShade(TShade.DEFAULT), false).register(),
    ...new ThemeVariable('listItemBgOpacityHover', asOpacity(5), false).register(),
    ...new ThemeVariable('listItemBgShadeFocus', asShade(TShade.DEFAULT), false).register(),
    ...new ThemeVariable('listItemBgOpacityFocus', asOpacity(5), false).register(),
    ...new ThemeVariable('listItemBgShadeActive', asShade(TShade.BRIGHT), false).register(),
    ...new ThemeVariable('listItemBgOpacityActive', asOpacity(5), false).register(),
    ...new ThemeVariable('listItemBgShadeActiveHover', asShade(TShade.BRIGHT), false).register(),
    ...new ThemeVariable('listItemBgOpacityActiveHover', asOpacity(10), false).register(),
    ...new ThemeVariable('listItemBgShadeFocused', asShade(TShade.PALE), false).register(),
    ...new ThemeVariable('listItemBgOpacityFocused', asOpacity(10), false).register(),
    ...new ThemeVariable('listItemBgShadeDisabled', asShade(TShade.DIMM), false).register(),
    ...new ThemeVariable('listItemBgOpacityDisabled', asOpacity(5), false).register(),
    ...new ThemeVariable('listItemColorShade', asShade(TShade.DEFAULT), false).register(),
    ...new ThemeVariable('listItemColorOpacity', asOpacity(80), false).register(),
    ...new ThemeVariable('listItemColorShadeHover', asShade(TShade.DEFAULT), false).register(),
    ...new ThemeVariable('listItemColorOpacityHover', asOpacity(100), false).register(),
    ...new ThemeVariable('listItemColorShadeFocus', asShade(TShade.DEFAULT), false).register(),
    ...new ThemeVariable('listItemColorOpacityFocus', asOpacity(100), false).register(),
    ...new ThemeVariable('listItemColorShadeActive', asShade(TShade.DEFAULT), false).register(),
    ...new ThemeVariable('listItemColorOpacityActive', asOpacity(100), false).register(),
    ...new ThemeVariable('listItemColorShadeActiveHover', asShade(TShade.DEFAULT), false).register(),
    ...new ThemeVariable('listItemColorOpacityActiveHover', asOpacity(100), false).register(),
    ...new ThemeVariable('listItemColorShadeFocused', asShade(TShade.DEFAULT), false).register(),
    ...new ThemeVariable('listItemColorOpacityFocused', asOpacity(90), false).register(),
    ...new ThemeVariable('listItemColorShadeDisabled', asShade(TShade.DEFAULT), false).register(),
    ...new ThemeVariable('listItemColorOpacityDisabled', asOpacity(50), false).register(),
  };

  return {
    ...app,
    ...mainTable,
    ...windows,
    ...inputs,
    ...messages,
    ...tags,
    ...videoPlayer,
    ...waveforms,
    ...controlPanel,
    ...tables,
    ...forms,
    ...tooltip,
    ...emojiPicker,
    ...listItem,
  };
};
